version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "bgreenawald"
    reviewers:
      - "bgreenawald"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge low-risk updates
    allow:
      - dependency-type: "direct:production"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct:development"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct:development"
        update-type: "version-update:semver-minor"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"